version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ps
    environment:
      POSTGRES_USER: ${DB_USER:-area_check_db}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: studs
    ports:
      - "5432:5432"
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: